
version: '3.1'

services:

  # Use postgres/postgres user/password credentials
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgsql :/var/lib/postgresql/data
  
  # Use root/example as user/password credentials
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3307:3307
    volumes:
      - ./mysql :/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
