version: '3.5'

services:

  # Use postgres/postgres user/password credentials
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgsql :/var/lib/postgresql/data
    # network_mode: bridge
  
  # Use root/mysql as user/password credentials
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql :/var/lib/mysql
    # network_mode: bridge

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8888:8080
    # network_mode: bridge


  reids:
    container_name: redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data